<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VoiceTyper.Core/VoiceTyper.Core.csproj" />
    <ProjectReference Include="../VoiceTyper.Windows/VoiceTyper.Windows.csproj" />
    <ProjectReference Include="../VoiceTyper.Volcengine/VoiceTyper.Volcengine.csproj" />
  </ItemGroup>
</Project>
