<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup><ProjectReference Include="../VoiceTyper.Core/VoiceTyper.Core.csproj" /></ItemGroup>
  <ItemGroup><Using Include="System.IO" /></ItemGroup>
  <ItemGroup><PackageReference Include="NAudio.Wasapi" Version="2.2.1" /><PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" /></ItemGroup>
</Project>

